// Truthful service area for HR Greenroots Landscaping.
// Source: contact.serviceAreas in lib/full-site-data.js (verified client copy).
// Each entry must reflect a real geographic area the business serves.
// Adding a city here without client confirmation = doorway-page risk.

export const locations = [
  {
    slug: "mississauga",
    name: "Mississauga",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L4Z",
    neighborhoods: ["Port Credit", "Streetsville", "Erin Mills", "Meadowvale", "Square One", "Lakeview", "Cooksville", "Clarkson"],
    adjacentCities: ["toronto", "brampton", "etobicoke", "oakville"],
    isHQ: true,
    headline: "Landscaping in Mississauga, ON",
  },
  {
    slug: "toronto",
    name: "Toronto",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "M5V",
    neighborhoods: ["Downtown Toronto", "Beaches", "Leslieville", "High Park", "Forest Hill", "Rosedale"],
    adjacentCities: ["mississauga", "etobicoke", "north-york", "scarborough"],
    headline: "Landscaping in Toronto, ON",
  },
  {
    slug: "brampton",
    name: "Brampton",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L6T",
    neighborhoods: ["Bramalea", "Heart Lake", "Mount Pleasant", "Springdale", "Castlemore"],
    adjacentCities: ["mississauga", "etobicoke", "newmarket"],
    headline: "Landscaping in Brampton, ON",
  },
  {
    slug: "richmond-hill",
    name: "Richmond Hill",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L4B",
    neighborhoods: ["Oak Ridges", "Bayview Hill", "Mill Pond", "Jefferson"],
    adjacentCities: ["thornhill", "aurora", "newmarket", "north-york"],
    headline: "Landscaping in Richmond Hill, ON",
  },
  {
    slug: "north-york",
    name: "North York",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "M2N",
    neighborhoods: ["Willowdale", "Don Mills", "Bayview Village", "Lawrence Park", "York Mills"],
    adjacentCities: ["toronto", "thornhill", "scarborough", "etobicoke"],
    headline: "Landscaping in North York, ON",
  },
  {
    slug: "thornhill",
    name: "Thornhill",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L4J",
    neighborhoods: ["Royal Orchard", "Thornhill Woods", "German Mills"],
    adjacentCities: ["richmond-hill", "north-york"],
    headline: "Landscaping in Thornhill, ON",
  },
  {
    slug: "etobicoke",
    name: "Etobicoke",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "M9C",
    neighborhoods: ["The Kingsway", "Mimico", "Long Branch", "Humber Bay", "Markland Wood"],
    adjacentCities: ["toronto", "mississauga", "north-york"],
    headline: "Landscaping in Etobicoke, ON",
  },
  {
    slug: "scarborough",
    name: "Scarborough",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "M1B",
    neighborhoods: ["Agincourt", "Bridlewood", "Cliffside", "Guildwood", "Highland Creek"],
    adjacentCities: ["toronto", "north-york", "ajax"],
    headline: "Landscaping in Scarborough, ON",
  },
  {
    slug: "ajax",
    name: "Ajax",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L1S",
    neighborhoods: ["Pickering Village", "Westney Heights", "South Ajax"],
    adjacentCities: ["oshawa", "scarborough"],
    headline: "Landscaping in Ajax, ON",
  },
  {
    slug: "oshawa",
    name: "Oshawa",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L1G",
    neighborhoods: ["Downtown Oshawa", "Lakeview", "Eastdale", "Northglen"],
    adjacentCities: ["ajax"],
    headline: "Landscaping in Oshawa, ON",
  },
  {
    slug: "niagara-region",
    name: "Niagara Region",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L2E",
    neighborhoods: ["Niagara Falls", "St. Catharines", "Welland", "Niagara-on-the-Lake"],
    adjacentCities: ["cambridge"],
    headline: "Landscaping in the Niagara Region, ON",
    note: "Travel surcharge may apply outside Mississauga / GTA core.",
  },
  {
    slug: "guelph",
    name: "Guelph",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "N1G",
    neighborhoods: ["Downtown Guelph", "South End", "Westminster Woods", "Old University"],
    adjacentCities: ["cambridge", "kitchener"],
    headline: "Landscaping in Guelph, ON",
  },
  {
    slug: "cambridge",
    name: "Cambridge",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "N1R",
    neighborhoods: ["Galt", "Preston", "Hespeler"],
    adjacentCities: ["kitchener", "guelph"],
    headline: "Landscaping in Cambridge, ON",
  },
  {
    slug: "kitchener",
    name: "Kitchener",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "N2G",
    neighborhoods: ["Downtown Kitchener", "Stanley Park", "Forest Heights", "Doon"],
    adjacentCities: ["cambridge", "guelph"],
    headline: "Landscaping in Kitchener, ON",
  },
  {
    slug: "london",
    name: "London",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "N6A",
    neighborhoods: ["Old North", "Byron", "Masonville", "Westmount", "Hyde Park"],
    adjacentCities: [],
    headline: "Landscaping in London, ON",
    note: "Larger projects only — travel time factored into estimate.",
  },
  {
    slug: "newmarket",
    name: "Newmarket",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L3Y",
    neighborhoods: ["Stonehaven", "Glenway", "Bristol-London", "Summerhill Estates"],
    adjacentCities: ["aurora", "richmond-hill"],
    headline: "Landscaping in Newmarket, ON",
  },
  {
    slug: "aurora",
    name: "Aurora",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L4G",
    neighborhoods: ["Aurora Highlands", "Hills of St. Andrew", "Bayview Northeast"],
    adjacentCities: ["newmarket", "richmond-hill"],
    headline: "Landscaping in Aurora, ON",
  },
  {
    slug: "barrie",
    name: "Barrie",
    region: "Ontario",
    regionShort: "ON",
    country: "Canada",
    postalPrefix: "L4M",
    neighborhoods: ["Allandale", "South Shore", "Painswick", "Innishore"],
    adjacentCities: [],
    headline: "Landscaping in Barrie, ON",
    note: "Larger projects only — travel time factored into estimate.",
  },
];

export const locationsBySlug = Object.fromEntries(
  locations.map((loc) => [loc.slug, loc])
);

export function getLocationBySlug(slug) {
  return locationsBySlug[slug] ?? null;
}

export function getAdjacentLocations(slug, limit = 3) {
  const loc = getLocationBySlug(slug);
  if (!loc) return [];
  return loc.adjacentCities
    .map((adjSlug) => getLocationBySlug(adjSlug))
    .filter(Boolean)
    .slice(0, limit);
}
